### ISSUE TITLE
Describing siblings between generic instances

### ISSUE THREAD

**Issue by dzervas** [tiesselune/sled-entity#14]
Heyo,

I'm migrating from sqlx (sqlite) for my project [magicentry](https://github.com/dzervas/magicentry) to reindeer and I can't quite wrap my head around the siblings vs deletion behavior

I have a generic struct that points to an instance of itself:

```rust
#[derive(Entity, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[entity(name = "token", id = "code", version = 1)]
#[siblings(("token", BreakLink))]
#[non_exhaustive]
pub struct Token<K: TokenKindType> {
	pub code: String,
	_kind: PhantomData<K>,
	pub user: String,
	pub expires_at: NaiveDateTime,
	pub bound_to: Option<String>,
	pub metadata: Option<String>,
}
```

There are two points of interest:

1. `TokenKindType` which is a trait that a bunch of macro-generated empty structs implement
2. `bound_to` which is essentially the `code` field of another `Token` which could be of any `TokenKindType`

my use case requires that a `Token<ScopedLogin>` is a child of `Token<Session>` but a `Token<OIDCBearer>` has no siblings

how can I describe that?

the whole `token` model lives in `src/token.rs` file if you want more context

BTW: amazing project. it was EXACTLY what I was searching for. I was using SQLite as a KV store already but I wanted to stop using sys packages (cross-compilation nightmare). I hope you get some traction to get that dopamine rolling :smiley_cat: 

BTW2: Since I'm using the `_kind` as `PhantomData`, does reindeer still ensure type safety? (in memory all `Token` types have the exact same representation)

**Comment by tiesselune** [comment]
Hello @dzervas !

Cool, someone is using my project! Great! Thanks for your interest ! :)

First, for tokens being children of other tokens : Children have the ID of their parent at the beggining of theirs, making it very quick to look for them. Siblings, on the other hand, share the exact same ID in different stores, making it easy to separate related data into 2 (or more) entries of different stores, so that the whole thing does not have to be serialized/ deserialized if you only want part of the data. (ex : `user_profile` and `user_picture` could be stored separately so each time you want to read/write the username, you don't have to read/write the whole profile picture.) So two sibling entities need to have the exact same id, which means that any `Token` should be sibling to itself... Not really useful :)

I think what you want is [free relations](https://github.com/tiesselune/reindeer-rs?tab=readme-ov-file#free-relations), the third type of relation, that are mapped using an intermediate store, the way association tables work in SQL. It's a lot more flexible but it's making the compromise of making more than I simple read or write operation when you follow the relation. This can be done between any kinds of entity, even betwen `Token` and `Token` itself, and it can define deletion behaviour for deleting it in both ways, which will help you define if deleting entity1 means automatically deleting entity 2, and vice-versa.

With free relations you can do pretty much whatever you like; it's a more conventional way of handling data relations. Parent and sibling relationships are really there to improve performance without too much fuss in those specific cases where they fit.

About type safety, I don't really know if (and if yes, how) `serde` (which I use for serialization) handles `PhantomData`, since it's supposed to be zero-sized. So if you try to read from the "token" store with the wrong `TokenKindType` type, it might just work without giving you a warning. In the end, it's really the store name that maps into a type, from `reindeer`'s point of vue. If you try it I'm interested in knowing the answer, though :)

**Comment by dzervas** [comment]
oh I completely missed free relations! it's exactly what I'm looking for!

I'll test `PhantomData` soon
